### ISSUE TITLE
ubuntu cloud images for XO 

### ISSUE THREAD

**Issue by babatundebusari** [scottalanmiller/xenorchestra_installer#2]
i know this is not related but no other way to get in touch with you
i am looking for ubuntu cloudinit images/templates for XO/XenServer but been unable to get one

Tried following the guide for the debian https://xen-orchestra.com/blog/debian-cloud-template-for-xenserver/ but its not exactly same so was not successful

**Comment by Jarli01** [comment]
What isn't working with the guide from the XO website, where are you encountering issues?

**Comment by babatundebusari** [comment]
What is not working is that XO website only has debian cloud image, and i am asking about ubuntu cloud image.

What is not working is creating an ubuntu cloud image
Ubuntu is more popular than debian, so have no idea why that for some reason is made but ubuntu is not. Anyways i tried following the guide, makes an image and it just does not work.

If anyone has a working ubuntu cloud image and want to share the steps(which are very small steps to be honest like install cloudinit and how they set it up before converting to template), that will be great

**Comment by babatundebusari** [comment]
finally works
i was checking the wrong thing when configuring cloudinit

In ubuntu the config drive is named `ConfigDrive: Reads data from Openstack Config Drive`
and that is all needed to be checked
